[shell]
program = "/usr/bin/zsh"
args = ["-l"]

[window]
decorations = "none"
opacity = 0.5

[mouse]
hide_when_typing = true

[font]
size = 12.0

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
style  = "Regular"

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
style  = "Bold"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style  = "Italic"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style  = "Bold Italic"
